load('../../lib/Tiltfile', 'files')

docker_build(
    'bar',
    context='.',
    dockerfile='Dockerfile',
)

k8s_yaml(files('manifests/*.yaml'))

k8s_resource(
    'bar',
    objects=[
        'bar:serviceaccount',
        'bar-root-inbound:httproute',
        'bar:server',
        'bar:serverauthorization',
    ],
    labels=['app'],
    resource_deps=['linkerd-control-plane']
)
