k8s_yaml("manifests.yaml")

docker_build(
    'bar',
    context='.',
    dockerfile='Dockerfile',
)

k8s_resource(
    'bar',
    objects=[
        'bar:serviceaccount',
        'bar-root-route:httproute',
        'bar:server',
        'bar-from-foo:serverauthorization',
    ],
    labels=['app'],
    resource_deps=['linkerd-control-plane']
)
