k8s_yaml("manifests.yaml")

docker_build(
    'baz',
    context='.',
    dockerfile='Dockerfile',
)

k8s_resource(
    'baz',
    labels=['app'],
    objects=[
        'baz:serviceaccount',
        'baz-root-route:httproute',
        'baz:server',
        'baz-from-foo:serverauthorization',
    ],
    resource_deps=['linkerd-control-plane'],
)
