load('ext://helm_resource', 'helm_resource', 'helm_repo')

local('kubectl get ns linkerd || kubectl create ns linkerd')
local('kubectl get ns linkerd-viz || kubectl create ns linkerd-viz')
local('kubectl annotate ns default linkerd.io/inject=enabled')

helm_repo(
    'linkerd-edge',
    'https://helm.linkerd.io/edge',
    resource_name='linkerd-chart',
    labels=['linkerd']
)

helm_resource(
    'linkerd-crds',
    'linkerd-edge/linkerd-crds',
    namespace='linkerd',
    resource_deps=['linkerd-chart'],
    release_name='linkerd-crds',
    labels=['linkerd'],
    pod_readiness='ignore'
)

helm_resource(
    'linkerd-control-plane',
    'linkerd-edge/linkerd-control-plane',
    namespace='linkerd',
    resource_deps=['linkerd-chart', 'linkerd-crds'],
    release_name='linkerd-control-plane',
    labels=['linkerd'],
    flags=[
        '--set-file', 'identityTrustAnchorsPEM=ca.crt',
        '--set-file', 'identity.issuer.tls.crtPEM=issuer.crt',
        '--set-file', 'identity.issuer.tls.keyPEM=issuer.key',
        '--set', 'proxyInit.runAsRoot=true'
    ]
)

helm_resource(
    'linkerd-viz',
    'linkerd-edge/linkerd-viz',
    namespace='linkerd-viz',
    resource_deps=['linkerd-chart', 'linkerd-control-plane'],
    release_name='linkerd-viz',
    port_forwards=['8084:8084', '9994:9994'],
    labels=['linkerd'],
    flags=[
        '--set', 'grafana.url=grafana.grafana:3000',
    ],
    links=[
        link('http://linkerd.localhost:5050', 'linkerd.localhost'),
    ]
)

# Add an ingress resource for linkerd-viz web
k8s_yaml('manifests.yaml')
k8s_resource(
    new_name='linkerd-viz-ext',
    objects=[
        'linkerd-viz:ingress',
        'prometheus-grafana-admin:AuthorizationPolicy'
    ],
    labels=['linkerd']
)